name: emisora_flutter_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.6
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  google_sign_in: ^5.4.4
  googleapis: ^10.0.0
  googleapis_auth: ^1.3.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.7
  package_google_sign_in:
    git:
      url: https://github.com/rodolgira/package_google_sign_in.git

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
