// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBugT7BIUK1FlSOsN8HV15UtqJsD9Ki1K0',
    appId: '1:42448997363:web:f3322a7b3e6f502bc2e086',
    messagingSenderId: '42448997363',
    projectId: 'login-with-b510f',
    authDomain: 'login-with-b510f.firebaseapp.com',
    storageBucket: 'login-with-b510f.appspot.com',
    measurementId: 'G-TY4L7XGRGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDftCmAxKncxsBv2Kk2FEdaakrVW0aX2Cs',
    appId: '1:42448997363:android:d21c731e2bbb1047c2e086',
    messagingSenderId: '42448997363',
    projectId: 'login-with-b510f',
    storageBucket: 'login-with-b510f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnoPg_lVnl3rzQft1lTqch_zO40MDhqn4',
    appId: '1:42448997363:ios:4e260e0ab4349b39c2e086',
    messagingSenderId: '42448997363',
    projectId: 'login-with-b510f',
    storageBucket: 'login-with-b510f.appspot.com',
    androidClientId: '42448997363-0kunmucojgsqtkvl9a9299gbmjjthj3a.apps.googleusercontent.com',
    iosClientId: '42448997363-d2ig303vhchnn21s7sqoarjaic2hqm21.apps.googleusercontent.com',
    iosBundleId: 'com.rodolfog.localFlutterLoginGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnoPg_lVnl3rzQft1lTqch_zO40MDhqn4',
    appId: '1:42448997363:ios:12f31d26896ad5b8c2e086',
    messagingSenderId: '42448997363',
    projectId: 'login-with-b510f',
    storageBucket: 'login-with-b510f.appspot.com',
    androidClientId: '42448997363-0kunmucojgsqtkvl9a9299gbmjjthj3a.apps.googleusercontent.com',
    iosClientId: '42448997363-o3oira8j3qk27a6gj468eb8ddebosh40.apps.googleusercontent.com',
    iosBundleId: 'com.example.emisoraFlutterApp',
  );
}
